// we are importing this as staticData which is an object.
// we need to use staticData and a dot to access the object's contents
// ex: staticData.charHex2Names['0x00'] will return 'Ryu'
const characters_Hex_2_Names = {
    '0x00': 'Ryu',
    '0x01': 'Zangief',
    '0x02': 'Guile',
    '0x03': 'Morrigan',
    '0x04': 'Anakaris',
    '0x05': 'Strider Hiryu',
    '0x06': 'Cyclops',
    '0x07': 'Wolverine',
    '0x08': 'Psylocke',
    '0x09': 'Iceman',
    '0x0a': 'Rogue',
    '0x0b': 'Captain America',
    '0x0c': 'Spider-Man',
    '0x0d': 'Hulk',
    '0x0e': 'Venom',
    '0x0f': 'Doctor Doom',
    '0x10': 'Tron Bonne',
    '0x11': 'Jill',
    '0x12': 'Hayato',
    '0x13': 'Ruby Heart',
    '0x14': 'Sonson',
    '0x15': 'Amingo',
    '0x16': 'Marrow',
    '0x17': 'Cable',
    '0x18': 'Abyss-A',
    '0x19': 'Abyss-B',
    '0x1a': 'Abyss-C',
    '0x1b': 'Chun-Li',
    '0x1c': 'Megaman',
    '0x1d': 'Roll',
    '0x1e': 'Akuma',
    '0x1f': 'B.B. Hood',
    '0x20': 'Felicia',
    '0x21': 'Charlie',
    '0x22': 'Sakura',
    '0x23': 'Dan',
    '0x24': 'Cammy',
    '0x25': 'Dhalsim',
    '0x26': 'M.Bison',
    '0x27': 'Ken',
    '0x28': 'Gambit',
    '0x29': 'Juggernaut',
    '0x2a': 'Storm',
    '0x2b': 'Sabretooth',
    '0x2c': 'Magneto',
    '0x2d': 'Shuma-Gorath',
    '0x2e': 'War Machine',
    '0x2f': 'Silver Samurai',
    '0x30': 'Omega Red',
    '0x31': 'Spiral',
    '0x32': 'Colossus',
    '0x33': 'Iron Man',
    '0x34': 'Sentinel',
    '0x35': 'Blackheart',
    '0x36': 'Thanos',
    '0x37': 'Jin',
    '0x38': 'Captain Commando',
    '0x39': 'Wolverine-B',
    '0x3a': 'Servbot'
};

exports.charHex2Names = characters_Hex_2_Names;