// Make an object with string type for key and value
// interface StringMap {[key: string]: string;}
export const characters_Hex_2_Names: { [key: string]: string; } = {
  '0x00': 'Ryu',
  '0x01': 'Zangief',
  '0x02': 'Guile',
  '0x03': 'Morrigan',
  '0x04': 'Anakaris',
  '0x05': 'Strider Hiryu',
  '0x06': 'Cyclops',
  '0x07': 'Wolverine',
  '0x08': 'Psylocke',
  '0x09': 'Iceman',
  '0x0a': 'Rogue',
  '0x0b': 'Captain America',
  '0x0c': 'Spider-Man',
  '0x0d': 'Hulk',
  '0x0e': 'Venom',
  '0x0f': 'Doctor Doom',
  '0x10': 'Tron Bonne',
  '0x11': 'Jill',
  '0x12': 'Hayato',
  '0x13': 'Ruby Heart',
  '0x14': 'Sonson',
  '0x15': 'Amingo',
  '0x16': 'Marrow',
  '0x17': 'Cable',
  '0x18': 'Abyss-A',
  '0x19': 'Abyss-B',
  '0x1a': 'Abyss-C',
  '0x1b': 'Chun-Li',
  '0x1c': 'Megaman',
  '0x1d': 'Roll',
  '0x1e': 'Akuma',
  '0x1f': 'B.B. Hood',
  '0x20': 'Felicia',
  '0x21': 'Charlie',
  '0x22': 'Sakura',
  '0x23': 'Dan',
  '0x24': 'Cammy',
  '0x25': 'Dhalsim',
  '0x26': 'M.Bison',
  '0x27': 'Ken',
  '0x28': 'Gambit',
  '0x29': 'Juggernaut',
  '0x2a': 'Storm',
  '0x2b': 'Sabretooth',
  '0x2c': 'Magneto',
  '0x2d': 'Shuma-Gorath',
  '0x2e': 'War Machine',
  '0x2f': 'Silver Samurai',
  '0x30': 'Omega Red',
  '0x31': 'Spiral',
  '0x32': 'Colossus',
  '0x33': 'Iron Man',
  '0x34': 'Sentinel',
  '0x35': 'Blackheart',
  '0x36': 'Thanos',
  '0x37': 'Jin',
  '0x38': 'Captain Commando',
  '0x39': 'Wolverine-B',
  '0x3a': 'Servbot'
};
export const ASM_DEF: { [key: string]: string; } = {
  'add': 'Adds the second argument to the first argument.',
  'sub': 'Subtracts the second argument from the first argument.',
  'xor': 'XORs the first argument with the second argument.',
  'bf': 'Bitfield. Sets the bits of the first argument to the value of the second argument',
  'cmp/eq': 'Compares the first argument with the second argument and sets the EQ flag if they are equal.',
  'bt': 'Bit test. Tests the first argument against the second argument.',
  'jmp': 'Jumps to the address of the first argument.',
  'tst': 'Tests the first argument against the second argument.',
  'jsr': 'Jumps to the address of the first argument.',
  'bra': 'Branches to the address of the first argument.',
  'bne': 'Branches to the address of the first argument if the EQ flag is not set.',
  'bge': 'Branches to the address of the first argument if the EQ flag is set.',
  'lds': 'Loads the value of the first argument into the second argument.',
  'lds.b': 'Loads a byte value into the second argument (which is 1 byte).',
  'lds.w': 'Loads a word value into the second argument (which is 2 bytes).',
  'lds.l': 'Loads a long value into the second argument (which is 4 bytes).',
  'sts': 'Stores the value of the first argument into the second argument.',
  'rts': 'Returns from a subroutine.',
  'shl': 'Shifts the first argument left by the second argument bits.',
  'shll': 'Shifts the first argument right by the second argument bits.',
  'shr': 'Shifts the first argument right by the second argument bits.',
  'shll2': 'Shifts the first argument left by 2 bits.',
  'shlr2': 'Shifts the first argument right by 2 bits.',
  'exts': 'Sign extends the first argument to the second argument size.',
  'extu': 'Zero extends the first argument to the second argument size.',
  'ext.b': 'Sign extends the first argument to 1 byte.',
  'nop': 'No operation.',
  'mov': 'Moves the value of the second argument into the first argument.',
  'mov.b': 'Moves a byte value into the first argument (which is 1 byte).',
  'mov.w': 'Moves a word value into the first argument (which is 2 bytes).',
  'mov.l': 'Moves a long value into the first argument (which is 4 bytes).',
  // Registers
  'r0': 'Register 0.',
  'r1': 'Register 1.',
  'r2': 'Register 2.',
  'r3': 'Register 3.',
  'r4': 'Register 4.',
  'r5': 'Register 5.',
  'r6': 'Register 6.',
  'r7': 'Register 7.',
  'r8': 'Register 8.',
  'r9': 'Register 9.',
  'r10': 'Register 10.',
  'r11': 'Register 11.',
  'r12': 'Register 12.',
  'r13': 'Register 13.',
  'r14': 'Register 14.',
  'r15': 'Register 15.',
  'new RegExp(\'^r[0-9]+$\')': 'Any register.',
  'PC': 'The program counter.',
  // Special matches
  '#align': 'Aligns the next instruction.',
  'label': 'A custom label.',
  '@': 'The current address. Points to the instruction.',
};
export const MVC2GEN_CONSTANTS: string[] = [
  // Names
  'Ryu',
  'Zangief',
  'Guile',
  'Morrigan',
  'Anakaris',
  'Strider Hiryu',
  'Cyclops',
  'Wolverine',
  'Psylocke',
  'Iceman',
  'Rogue',
  'Captain America',
  'Spider-Man',
  'Hulk',
  'Venom',
  'Doctor Doom',
  'Tron Bonne',
  'Jill',
  'Hayato',
  'Ruby Heart',
  'Sonson',
  'Amingo',
  'Marrow',
  'Cable',
  'Abyss-A',
  'Abyss-B',
  'Abyss-C',
  'Chun-Li',
  'Megaman',
  'Roll',
  'Akuma',
  'B.B. Hood',
  'Felicia',
  'Charlie',
  'Sakura',
  'Dan',
  'Cammy',
  'Dhalsim',
  'M.Bison',
  'Ken',
  'Gambit',
  'Juggernaut',
  'Storm',
  'Sabretooth',
  'Magneto',
  'Shuma-Gorath',
  'War Machine',
  'Silver Samurai',
  'Omega Red',
  'Spiral',
  'Colossus',
  'Iron Man',
  'Sentinel',
  'Blackheart',
  'Thanos',
  'Jin',
  'Captain Commando',
  'Wolverine-B',
  'Servbot',
  // P1P2+ Addresses
  'A_2D_Game_Timer',
  'Camera_Field_of_View',
  'Camera_X_Position',
  'Camera_X_Rotation',
  'Camera_Y_Position',
  'Camera_Y_Rotation',
  'Frame_Skip_Counter',
  'Frame_Skip_Cycle_Value',
  'Frame_Skip_Rate',
  'Frame_Skip_Toggle',
  'Is_Paused',
  'Match_Start_Throw_Timer',
  'Match_Tracker',
  'P1_Assist_Flag',
  'P1_Attacks_Done',
  'P1_Attacks_Successful',
  'P1_Combo_Meter_Value',
  'P1_Hitbox_Count',
  'P1_Max_Combo',
  'P1_Meter_Big',
  'P1_Meter_Small',
  'P1_Pause_ID',
  'P2_Assist_Flag',
  'P2_Attacks_Done',
  'P2_Attacks_Successful',
  'P2_Combo_Meter_Value',
  'P2_Hitbox_Count',
  'P2_Max_Combo',
  'P2_Meter_Big',
  'P2_Meter_Small',
  'P2_Pause_ID',
  'Pause_Count',
  'Stage_Selector',
  'Timer_Secondary',
  'Total_Frames',
  // Player Memory
  // * * * P1_A_ * * * //
  'P1_A_Anakaris_SStun_Timer',
  'P1_A_Bison_214kk_Timer',
  'P1_A_Cable_236p_Timer',
  'P1_A_Dhalsim_214kk_Timer',
  'P1_A_Doom_214kk_Timer',
  'P1_A_Iron_Man_214kk_Timer',
  'P1_A_Magneto_214kk_Timer',
  'P1_A_Megaman_214kk_Timer',
  'P1_A_Sentinel_214kk_Timer',
  'P1_A_Storm_214kk_Timer',
  'P1_A_War_Machine_214kk_Timer',
  'P1_A_X_Position_From_Enemy',
  'P1_A_Y_Position_From_Enemy',
  'P1_A_X_Gravity',
  'P1_A_Y_Gravity',
  'P1_A_X_Position_Arena',
  'P1_A_Y_Position_Arena',
  'P1_A_X_Position_Screen',
  'P1_A_Y_Position_Screen',
  'P1_A_X_Velocity',
  'P1_A_Y_Velocity',
  'P1_A_Action_Flags',
  'P1_A_Air_Dash_Count',
  'P1_A_Air_Recovery_Timer',
  'P1_A_Airborne',
  'P1_A_Animation_Lock',
  'P1_A_Animation_Timer_Main',
  'P1_A_Animation_Value',
  'P1_A_Assist_Counter',
  'P1_A_Assist_Onscreen',
  'P1_A_Assist_Value',
  'P1_A_Attack_Immune',
  'P1_A_Attack_Number',
  'P1_A_Block_Meter',
  'P1_A_Block_Stun',
  'P1_A_Color',
  'P1_A_CornerJump',
  'P1_A_Corner_Touch',
  'P1_A_Damage',
  'P1_A_Damage_Modifier',
  'P1_A_Defense_Modifier',
  'P1_A_Dizzy_Reset_Timer',
  'P1_A_Dizzy',
  'P1_A_Facing_Right',
  'P1_A_Flight_Flag',
  'P1_A_FlyingScreen',
  'P1_A_FSI_Combo',
  'P1_A_FSI_Points',
  'P1_A_FSI_Projectile',
  'P1_A_GuardBreak_Flag',
  'P1_A_Health_Big',
  'P1_A_Health_Small',
  'P1_A_Hitstop2',
  'P1_A_Hyper_Armor',
  'P1_A_ID_2',
  'P1_A_Idle_Hover',
  'P1_A_Is_Active',
  'P1_A_Is_Point',
  'P1_A_Is_Prox_Block',
  'P1_A_Jumping_Special_Counter',
  'P1_A_Jumps',
  'P1_A_Knockdown_State',
  'P1_A_Landing_Shake',
  'P1_A_Magneto_Throw_Toggle',
  'P1_A_Move_Disable',
  'P1_A_Normal_Held_Direction',
  'P1_A_Normal_Location',
  'P1_A_Normal_Strength',
  'P1_A_Powerup_Modifier',
  'P1_A_Powerup_Timer',
  'P1_A_ProxBlock',
  'P1_A_PunchKick',
  'P1_A_SJ_Counter',
  'P1_A_Snapback_Timer',
  'P1_A_Special_Attack_ID',
  'P1_A_Special_Strength',
  'P1_A_Speedup',
  'P1_A_Stun_Check',
  'P1_A_Super_Armor',
  'P1_A_Throw_Counter_Mash',
  'P1_A_Throw_Immune',
  'P1_A_Throw_Limiter',
  'P1_A_Throw_RNG',
  'P1_A_Trip_Checker',
  'P1_A_Unfly',
  'P1_A_Walking',
  'P1_A_X_Gravity_Max',
  'P1_A_X_Gravity_Min',
  'P1_A_X_Position_Arena_Max',
  'P1_A_X_Position_Arena_Min',
  'P1_A_X_Position_From_Enemy_Max',
  'P1_A_X_Position_From_Enemy_Min',
  'P1_A_X_Position_Screen_Max',
  'P1_A_X_Position_Screen_Min',
  'P1_A_Y_Gravity_Max',
  'P1_A_Y_Gravity_Min',
  'P1_A_Y_Position_Arena_Max',
  'P1_A_Y_Position_Arena_Min',
  'P1_A_Y_Position_From_Enemy_Max',
  'P1_A_Y_Position_From_Enemy_Min',
  'P1_A_Y_Position_Screen_Max',
  'P1_A_Y_Position_Screen_Min',
  'P1_A_X_Velocity_Max',
  'P1_A_X_Velocity_Min',
  'P1_A_Y_Velocity_Max',
  'P1_A_Y_Velocity_Min',
  'P1_A_Bison_214kk_Timer_Max',
  'P1_A_Bison_214kk_Timer_Min',
  'P1_A_Dhalsim_214kk_Timer_Max',
  'P1_A_Dhalsim_214kk_Timer_Min',
  'P1_A_Doom_214kk_Timer_Max',
  'P1_A_Doom_214kk_Timer_Min',
  'P1_A_Iron_Man_214kk_Timer_Max',
  'P1_A_Iron_Man_214kk_Timer_Min',
  'P1_A_Magneto_214kk_Timer_Max',
  'P1_A_Magneto_214kk_Timer_Min',
  'P1_A_Megaman_214kk_Timer_Max',
  'P1_A_Megaman_214kk_Timer_Min',
  'P1_A_Sentinel_214kk_Timer_Max',
  'P1_A_Sentinel_214kk_Timer_Min',
  'P1_A_Storm_214kk_Timer_Max',
  'P1_A_Storm_214kk_Timer_Min',
  'P1_A_War_Machine_214kk_Timer_Max',
  'P1_A_War_Machine_214kk_Timer_Min',
  'P1_A_X_Gravity_0',
  'P1_A_X_Gravity_Min_0',
  'P1_A_X_Gravity_Max_0',
  'P1_A_X_Position_Arena_0',
  'P1_A_X_Position_Arena_Min_0',
  'P1_A_X_Position_Arena_Max_0',
  'P1_A_X_Position_From_Enemy_0',
  'P1_A_X_Position_From_Enemy_Min_0',
  'P1_A_X_Position_From_Enemy_Max_0',
  'P1_A_X_Position_Screen_0',
  'P1_A_X_Position_Screen_Min_0',
  'P1_A_X_Position_Screen_Max_0',
  'P1_A_X_Velocity_0',
  'P1_A_X_Velocity_Min_0',
  'P1_A_X_Velocity_Max_0',
  'P1_A_Y_Gravity_0',
  'P1_A_Y_Gravity_Min_0',
  'P1_A_Y_Gravity_Max_0',
  'P1_A_Y_Position_Arena_0',
  'P1_A_Y_Position_Arena_Min_0',
  'P1_A_Y_Position_Arena_Max_0',
  'P1_A_Y_Position_From_Enemy_0',
  'P1_A_Y_Position_From_Enemy_Min_0',
  'P1_A_Y_Position_From_Enemy_Max_0',
  'P1_A_Y_Position_Screen_0',
  'P1_A_Y_Position_Screen_Min_0',
  'P1_A_Y_Position_Screen_Max_0',
  'P1_A_Y_Velocity_0',
  'P1_A_Y_Velocity_Min_0',
  'P1_A_Y_Velocity_Max_0',
  // * * * P1_B_ * * * //
  'P1_B_Anakaris_SStun_Timer',
  'P1_B_Bison_214kk_Timer',
  'P1_B_Cable_236p_Timer',
  'P1_B_Dhalsim_214kk_Timer',
  'P1_B_Doom_214kk_Timer',
  'P1_B_Iron_Man_214kk_Timer',
  'P1_B_Magneto_214kk_Timer',
  'P1_B_Megaman_214kk_Timer',
  'P1_B_Sentinel_214kk_Timer',
  'P1_B_Storm_214kk_Timer',
  'P1_B_War_Machine_214kk_Timer',
  'P1_B_X_Position_From_Enemy',
  'P1_B_Y_Position_From_Enemy',
  'P1_B_X_Gravity',
  'P1_B_Y_Gravity',
  'P1_B_X_Position_Arena',
  'P1_B_Y_Position_Arena',
  'P1_B_X_Position_Screen',
  'P1_B_Y_Position_Screen',
  'P1_B_X_Velocity',
  'P1_B_Y_Velocity',
  'P1_B_Action_Flags',
  'P1_B_Air_Dash_Count',
  'P1_B_Air_Recovery_Timer',
  'P1_B_Airborne',
  'P1_B_Animation_Lock',
  'P1_B_Animation_Timer_Main',
  'P1_B_Animation_Value',
  'P1_B_Assist_Counter',
  'P1_B_Assist_Onscreen',
  'P1_B_Assist_Value',
  'P1_B_Attack_Immune',
  'P1_B_Attack_Number',
  'P1_B_Block_Meter',
  'P1_B_Block_Stun',
  'P1_B_Color',
  'P1_B_CornerJump',
  'P1_B_Corner_Touch',
  'P1_B_Damage',
  'P1_B_Damage_Modifier',
  'P1_B_Defense_Modifier',
  'P1_B_Dizzy_Reset_Timer',
  'P1_B_Dizzy',
  'P1_B_Facing_Right',
  'P1_B_Flight_Flag',
  'P1_B_FlyingScreen',
  'P1_B_FSI_Combo',
  'P1_B_FSI_Points',
  'P1_B_FSI_Projectile',
  'P1_B_GuardBreak_Flag',
  'P1_B_Health_Big',
  'P1_B_Health_Small',
  'P1_B_Hitstop2',
  'P1_B_Hyper_Armor',
  'P1_B_ID_2',
  'P1_B_Idle_Hover',
  'P1_B_Is_Active',
  'P1_B_Is_Point',
  'P1_B_Is_Prox_Block',
  'P1_B_Jumping_Special_Counter',
  'P1_B_Jumps',
  'P1_B_Knockdown_State',
  'P1_B_Landing_Shake',
  'P1_B_Magneto_Throw_Toggle',
  'P1_B_Move_Disable',
  'P1_B_Normal_Held_Direction',
  'P1_B_Normal_Location',
  'P1_B_Normal_Strength',
  'P1_B_Powerup_Modifier',
  'P1_B_Powerup_Timer',
  'P1_B_ProxBlock',
  'P1_B_PunchKick',
  'P1_B_SJ_Counter',
  'P1_B_Snapback_Timer',
  'P1_B_Special_Attack_ID',
  'P1_B_Special_Strength',
  'P1_B_Speedup',
  'P1_B_Stun_Check',
  'P1_B_Super_Armor',
  'P1_B_Throw_Counter_Mash',
  'P1_B_Throw_Immune',
  'P1_B_Throw_Limiter',
  'P1_B_Throw_RNG',
  'P1_B_Trip_Checker',
  'P1_B_Unfly',
  'P1_B_Walking',
  'P1_B_X_Gravity_Max',
  'P1_B_X_Gravity_Min',
  'P1_B_X_Position_Arena_Max',
  'P1_B_X_Position_Arena_Min',
  'P1_B_X_Position_From_Enemy_Max',
  'P1_B_X_Position_From_Enemy_Min',
  'P1_B_X_Position_Screen_Max',
  'P1_B_X_Position_Screen_Min',
  'P1_B_Y_Gravity_Max',
  'P1_B_Y_Gravity_Min',
  'P1_B_Y_Position_Arena_Max',
  'P1_B_Y_Position_Arena_Min',
  'P1_B_Y_Position_From_Enemy_Max',
  'P1_B_Y_Position_From_Enemy_Min',
  'P1_B_Y_Position_Screen_Max',
  'P1_B_Y_Position_Screen_Min',
  'P1_B_X_Velocity_Max',
  'P1_B_X_Velocity_Min',
  'P1_B_Y_Velocity_Max',
  'P1_B_Y_Velocity_Min',
  'P1_B_Bison_214kk_Timer_Max',
  'P1_B_Bison_214kk_Timer_Min',
  'P1_B_Dhalsim_214kk_Timer_Max',
  'P1_B_Dhalsim_214kk_Timer_Min',
  'P1_B_Doom_214kk_Timer_Max',
  'P1_B_Doom_214kk_Timer_Min',
  'P1_B_Iron_Man_214kk_Timer_Max',
  'P1_B_Iron_Man_214kk_Timer_Min',
  'P1_B_Magneto_214kk_Timer_Max',
  'P1_B_Magneto_214kk_Timer_Min',
  'P1_B_Megaman_214kk_Timer_Max',
  'P1_B_Megaman_214kk_Timer_Min',
  'P1_B_Sentinel_214kk_Timer_Max',
  'P1_B_Sentinel_214kk_Timer_Min',
  'P1_B_Storm_214kk_Timer_Max',
  'P1_B_Storm_214kk_Timer_Min',
  'P1_B_War_Machine_214kk_Timer_Max',
  'P1_B_War_Machine_214kk_Timer_Min',
  'P1_B_X_Gravity_0',
  'P1_B_X_Gravity_Min_0',
  'P1_B_X_Gravity_Max_0',
  'P1_B_X_Position_Arena_0',
  'P1_B_X_Position_Arena_Min_0',
  'P1_B_X_Position_Arena_Max_0',
  'P1_B_X_Position_From_Enemy_0',
  'P1_B_X_Position_From_Enemy_Min_0',
  'P1_B_X_Position_From_Enemy_Max_0',
  'P1_B_X_Position_Screen_0',
  'P1_B_X_Position_Screen_Min_0',
  'P1_B_X_Position_Screen_Max_0',
  'P1_B_X_Velocity_0',
  'P1_B_X_Velocity_Min_0',
  'P1_B_X_Velocity_Max_0',
  'P1_B_Y_Gravity_0',
  'P1_B_Y_Gravity_Min_0',
  'P1_B_Y_Gravity_Max_0',
  'P1_B_Y_Position_Arena_0',
  'P1_B_Y_Position_Arena_Min_0',
  'P1_B_Y_Position_Arena_Max_0',
  'P1_B_Y_Position_From_Enemy_0',
  'P1_B_Y_Position_From_Enemy_Min_0',
  'P1_B_Y_Position_From_Enemy_Max_0',
  'P1_B_Y_Position_Screen_0',
  'P1_B_Y_Position_Screen_Min_0',
  'P1_B_Y_Position_Screen_Max_0',
  'P1_B_Y_Velocity_0',
  'P1_B_Y_Velocity_Min_0',
  'P1_B_Y_Velocity_Max_0',
  // * * * P1_C_ * * * //
  'P1_C_Anakaris_SStun_Timer',
  'P1_C_Bison_214kk_Timer',
  'P1_C_Cable_236p_Timer',
  'P1_C_Dhalsim_214kk_Timer',
  'P1_C_Doom_214kk_Timer',
  'P1_C_Iron_Man_214kk_Timer',
  'P1_C_Magneto_214kk_Timer',
  'P1_C_Megaman_214kk_Timer',
  'P1_C_Sentinel_214kk_Timer',
  'P1_C_Storm_214kk_Timer',
  'P1_C_War_Machine_214kk_Timer',
  'P1_C_X_Position_From_Enemy',
  'P1_C_Y_Position_From_Enemy',
  'P1_C_X_Gravity',
  'P1_C_Y_Gravity',
  'P1_C_X_Position_Arena',
  'P1_C_Y_Position_Arena',
  'P1_C_X_Position_Screen',
  'P1_C_Y_Position_Screen',
  'P1_C_X_Velocity',
  'P1_C_Y_Velocity',
  'P1_C_Action_Flags',
  'P1_C_Air_Dash_Count',
  'P1_C_Air_Recovery_Timer',
  'P1_C_Airborne',
  'P1_C_Animation_Lock',
  'P1_C_Animation_Timer_Main',
  'P1_C_Animation_Value',
  'P1_C_Assist_Counter',
  'P1_C_Assist_Onscreen',
  'P1_C_Assist_Value',
  'P1_C_Attack_Immune',
  'P1_C_Attack_Number',
  'P1_C_Block_Meter',
  'P1_C_Block_Stun',
  'P1_C_Color',
  'P1_C_CornerJump',
  'P1_C_Corner_Touch',
  'P1_C_Damage',
  'P1_C_Damage_Modifier',
  'P1_C_Defense_Modifier',
  'P1_C_Dizzy_Reset_Timer',
  'P1_C_Dizzy',
  'P1_C_Facing_Right',
  'P1_C_Flight_Flag',
  'P1_C_FlyingScreen',
  'P1_C_FSI_Combo',
  'P1_C_FSI_Points',
  'P1_C_FSI_Projectile',
  'P1_C_GuardBreak_Flag',
  'P1_C_Health_Big',
  'P1_C_Health_Small',
  'P1_C_Hitstop2',
  'P1_C_Hyper_Armor',
  'P1_C_ID_2',
  'P1_C_Idle_Hover',
  'P1_C_Is_Active',
  'P1_C_Is_Point',
  'P1_C_Is_Prox_Block',
  'P1_C_Jumping_Special_Counter',
  'P1_C_Jumps',
  'P1_C_Knockdown_State',
  'P1_C_Landing_Shake',
  'P1_C_Magneto_Throw_Toggle',
  'P1_C_Move_Disable',
  'P1_C_Normal_Held_Direction',
  'P1_C_Normal_Location',
  'P1_C_Normal_Strength',
  'P1_C_Powerup_Modifier',
  'P1_C_Powerup_Timer',
  'P1_C_ProxBlock',
  'P1_C_PunchKick',
  'P1_C_SJ_Counter',
  'P1_C_Snapback_Timer',
  'P1_C_Special_Attack_ID',
  'P1_C_Special_Strength',
  'P1_C_Speedup',
  'P1_C_Stun_Check',
  'P1_C_Super_Armor',
  'P1_C_Throw_Counter_Mash',
  'P1_C_Throw_Immune',
  'P1_C_Throw_Limiter',
  'P1_C_Throw_RNG',
  'P1_C_Trip_Checker',
  'P1_C_Unfly',
  'P1_C_Walking',
  'P1_C_X_Gravity_Max',
  'P1_C_X_Gravity_Min',
  'P1_C_X_Position_Arena_Max',
  'P1_C_X_Position_Arena_Min',
  'P1_C_X_Position_From_Enemy_Max',
  'P1_C_X_Position_From_Enemy_Min',
  'P1_C_X_Position_Screen_Max',
  'P1_C_X_Position_Screen_Min',
  'P1_C_Y_Gravity_Max',
  'P1_C_Y_Gravity_Min',
  'P1_C_Y_Position_Arena_Max',
  'P1_C_Y_Position_Arena_Min',
  'P1_C_Y_Position_From_Enemy_Max',
  'P1_C_Y_Position_From_Enemy_Min',
  'P1_C_Y_Position_Screen_Max',
  'P1_C_Y_Position_Screen_Min',
  'P1_C_X_Velocity_Max',
  'P1_C_X_Velocity_Min',
  'P1_C_Y_Velocity_Max',
  'P1_C_Y_Velocity_Min',
  'P1_C_Bison_214kk_Timer_Max',
  'P1_C_Bison_214kk_Timer_Min',
  'P1_C_Dhalsim_214kk_Timer_Max',
  'P1_C_Dhalsim_214kk_Timer_Min',
  'P1_C_Doom_214kk_Timer_Max',
  'P1_C_Doom_214kk_Timer_Min',
  'P1_C_Iron_Man_214kk_Timer_Max',
  'P1_C_Iron_Man_214kk_Timer_Min',
  'P1_C_Magneto_214kk_Timer_Max',
  'P1_C_Magneto_214kk_Timer_Min',
  'P1_C_Megaman_214kk_Timer_Max',
  'P1_C_Megaman_214kk_Timer_Min',
  'P1_C_Sentinel_214kk_Timer_Max',
  'P1_C_Sentinel_214kk_Timer_Min',
  'P1_C_Storm_214kk_Timer_Max',
  'P1_C_Storm_214kk_Timer_Min',
  'P1_C_War_Machine_214kk_Timer_Max',
  'P1_C_War_Machine_214kk_Timer_Min',
  'P1_C_X_Gravity_0',
  'P1_C_X_Gravity_Min_0',
  'P1_C_X_Gravity_Max_0',
  'P1_C_X_Position_Arena_0',
  'P1_C_X_Position_Arena_Min_0',
  'P1_C_X_Position_Arena_Max_0',
  'P1_C_X_Position_From_Enemy_0',
  'P1_C_X_Position_From_Enemy_Min_0',
  'P1_C_X_Position_From_Enemy_Max_0',
  'P1_C_X_Position_Screen_0',
  'P1_C_X_Position_Screen_Min_0',
  'P1_C_X_Position_Screen_Max_0',
  'P1_C_X_Velocity_0',
  'P1_C_X_Velocity_Min_0',
  'P1_C_X_Velocity_Max_0',
  'P1_C_Y_Gravity_0',
  'P1_C_Y_Gravity_Min_0',
  'P1_C_Y_Gravity_Max_0',
  'P1_C_Y_Position_Arena_0',
  'P1_C_Y_Position_Arena_Min_0',
  'P1_C_Y_Position_Arena_Max_0',
  'P1_C_Y_Position_From_Enemy_0',
  'P1_C_Y_Position_From_Enemy_Min_0',
  'P1_C_Y_Position_From_Enemy_Max_0',
  'P1_C_Y_Position_Screen_0',
  'P1_C_Y_Position_Screen_Min_0',
  'P1_C_Y_Position_Screen_Max_0',
  'P1_C_Y_Velocity_0',
  'P1_C_Y_Velocity_Min_0',
  'P1_C_Y_Velocity_Max_0',
  // * * * P2_A_ * * * //
  'P2_A_Anakaris_SStun_Timer',
  'P2_A_Bison_214kk_Timer',
  'P2_A_Cable_236p_Timer',
  'P2_A_Dhalsim_214kk_Timer',
  'P2_A_Doom_214kk_Timer',
  'P2_A_Iron_Man_214kk_Timer',
  'P2_A_Magneto_214kk_Timer',
  'P2_A_Megaman_214kk_Timer',
  'P2_A_Sentinel_214kk_Timer',
  'P2_A_Storm_214kk_Timer',
  'P2_A_War_Machine_214kk_Timer',
  'P2_A_X_Position_From_Enemy',
  'P2_A_Y_Position_From_Enemy',
  'P2_A_X_Gravity',
  'P2_A_Y_Gravity',
  'P2_A_X_Position_Arena',
  'P2_A_Y_Position_Arena',
  'P2_A_X_Position_Screen',
  'P2_A_Y_Position_Screen',
  'P2_A_X_Velocity',
  'P2_A_Y_Velocity',
  'P2_A_Action_Flags',
  'P2_A_Air_Dash_Count',
  'P2_A_Air_Recovery_Timer',
  'P2_A_Airborne',
  'P2_A_Animation_Lock',
  'P2_A_Animation_Timer_Main',
  'P2_A_Animation_Value',
  'P2_A_Assist_Counter',
  'P2_A_Assist_Onscreen',
  'P2_A_Assist_Value',
  'P2_A_Attack_Immune',
  'P2_A_Attack_Number',
  'P2_A_Block_Meter',
  'P2_A_Block_Stun',
  'P2_A_Color',
  'P2_A_CornerJump',
  'P2_A_Corner_Touch',
  'P2_A_Damage',
  'P2_A_Damage_Modifier',
  'P2_A_Defense_Modifier',
  'P2_A_Dizzy_Reset_Timer',
  'P2_A_Dizzy',
  'P2_A_Facing_Right',
  'P2_A_Flight_Flag',
  'P2_A_FlyingScreen',
  'P2_A_FSI_Combo',
  'P2_A_FSI_Points',
  'P2_A_FSI_Projectile',
  'P2_A_GuardBreak_Flag',
  'P2_A_Health_Big',
  'P2_A_Health_Small',
  'P2_A_Hitstop2',
  'P2_A_Hyper_Armor',
  'P2_A_ID_2',
  'P2_A_Idle_Hover',
  'P2_A_Is_Active',
  'P2_A_Is_Point',
  'P2_A_Is_Prox_Block',
  'P2_A_Jumping_Special_Counter',
  'P2_A_Jumps',
  'P2_A_Knockdown_State',
  'P2_A_Landing_Shake',
  'P2_A_Magneto_Throw_Toggle',
  'P2_A_Move_Disable',
  'P2_A_Normal_Held_Direction',
  'P2_A_Normal_Location',
  'P2_A_Normal_Strength',
  'P2_A_Powerup_Modifier',
  'P2_A_Powerup_Timer',
  'P2_A_ProxBlock',
  'P2_A_PunchKick',
  'P2_A_SJ_Counter',
  'P2_A_Snapback_Timer',
  'P2_A_Special_Attack_ID',
  'P2_A_Special_Strength',
  'P2_A_Speedup',
  'P2_A_Stun_Check',
  'P2_A_Super_Armor',
  'P2_A_Throw_Counter_Mash',
  'P2_A_Throw_Immune',
  'P2_A_Throw_Limiter',
  'P2_A_Throw_RNG',
  'P2_A_Trip_Checker',
  'P2_A_Unfly',
  'P2_A_Walking',
  'P2_A_X_Gravity_Max',
  'P2_A_X_Gravity_Min',
  'P2_A_X_Position_Arena_Max',
  'P2_A_X_Position_Arena_Min',
  'P2_A_X_Position_From_Enemy_Max',
  'P2_A_X_Position_From_Enemy_Min',
  'P2_A_X_Position_Screen_Max',
  'P2_A_X_Position_Screen_Min',
  'P2_A_Y_Gravity_Max',
  'P2_A_Y_Gravity_Min',
  'P2_A_Y_Position_Arena_Max',
  'P2_A_Y_Position_Arena_Min',
  'P2_A_Y_Position_From_Enemy_Max',
  'P2_A_Y_Position_From_Enemy_Min',
  'P2_A_Y_Position_Screen_Max',
  'P2_A_Y_Position_Screen_Min',
  'P2_A_X_Velocity_Max',
  'P2_A_X_Velocity_Min',
  'P2_A_Y_Velocity_Max',
  'P2_A_Y_Velocity_Min',
  'P2_A_Bison_214kk_Timer_Max',
  'P2_A_Bison_214kk_Timer_Min',
  'P2_A_Dhalsim_214kk_Timer_Max',
  'P2_A_Dhalsim_214kk_Timer_Min',
  'P2_A_Doom_214kk_Timer_Max',
  'P2_A_Doom_214kk_Timer_Min',
  'P2_A_Iron_Man_214kk_Timer_Max',
  'P2_A_Iron_Man_214kk_Timer_Min',
  'P2_A_Magneto_214kk_Timer_Max',
  'P2_A_Magneto_214kk_Timer_Min',
  'P2_A_Megaman_214kk_Timer_Max',
  'P2_A_Megaman_214kk_Timer_Min',
  'P2_A_Sentinel_214kk_Timer_Max',
  'P2_A_Sentinel_214kk_Timer_Min',
  'P2_A_Storm_214kk_Timer_Max',
  'P2_A_Storm_214kk_Timer_Min',
  'P2_A_War_Machine_214kk_Timer_Max',
  'P2_A_War_Machine_214kk_Timer_Min',
  'P2_A_X_Gravity_0',
  'P2_A_X_Gravity_Min_0',
  'P2_A_X_Gravity_Max_0',
  'P2_A_X_Position_Arena_0',
  'P2_A_X_Position_Arena_Min_0',
  'P2_A_X_Position_Arena_Max_0',
  'P2_A_X_Position_From_Enemy_0',
  'P2_A_X_Position_From_Enemy_Min_0',
  'P2_A_X_Position_From_Enemy_Max_0',
  'P2_A_X_Position_Screen_0',
  'P2_A_X_Position_Screen_Min_0',
  'P2_A_X_Position_Screen_Max_0',
  'P2_A_X_Velocity_0',
  'P2_A_X_Velocity_Min_0',
  'P2_A_X_Velocity_Max_0',
  'P2_A_Y_Gravity_0',
  'P2_A_Y_Gravity_Min_0',
  'P2_A_Y_Gravity_Max_0',
  'P2_A_Y_Position_Arena_0',
  'P2_A_Y_Position_Arena_Min_0',
  'P2_A_Y_Position_Arena_Max_0',
  'P2_A_Y_Position_From_Enemy_0',
  'P2_A_Y_Position_From_Enemy_Min_0',
  'P2_A_Y_Position_From_Enemy_Max_0',
  'P2_A_Y_Position_Screen_0',
  'P2_A_Y_Position_Screen_Min_0',
  'P2_A_Y_Position_Screen_Max_0',
  'P2_A_Y_Velocity_0',
  'P2_A_Y_Velocity_Min_0',
  'P2_A_Y_Velocity_Max_0',
  // * * * P2_B_ * * * //
  'P2_B_Anakaris_SStun_Timer',
  'P2_B_Bison_214kk_Timer',
  'P2_B_Cable_236p_Timer',
  'P2_B_Dhalsim_214kk_Timer',
  'P2_B_Doom_214kk_Timer',
  'P2_B_Iron_Man_214kk_Timer',
  'P2_B_Magneto_214kk_Timer',
  'P2_B_Megaman_214kk_Timer',
  'P2_B_Sentinel_214kk_Timer',
  'P2_B_Storm_214kk_Timer',
  'P2_B_War_Machine_214kk_Timer',
  'P2_B_X_Position_From_Enemy',
  'P2_B_Y_Position_From_Enemy',
  'P2_B_X_Gravity',
  'P2_B_Y_Gravity',
  'P2_B_X_Position_Arena',
  'P2_B_Y_Position_Arena',
  'P2_B_X_Position_Screen',
  'P2_B_Y_Position_Screen',
  'P2_B_X_Velocity',
  'P2_B_Y_Velocity',
  'P2_B_Action_Flags',
  'P2_B_Air_Dash_Count',
  'P2_B_Air_Recovery_Timer',
  'P2_B_Airborne',
  'P2_B_Animation_Lock',
  'P2_B_Animation_Timer_Main',
  'P2_B_Animation_Value',
  'P2_B_Assist_Counter',
  'P2_B_Assist_Onscreen',
  'P2_B_Assist_Value',
  'P2_B_Attack_Immune',
  'P2_B_Attack_Number',
  'P2_B_Block_Meter',
  'P2_B_Block_Stun',
  'P2_B_Color',
  'P2_B_CornerJump',
  'P2_B_Corner_Touch',
  'P2_B_Damage',
  'P2_B_Damage_Modifier',
  'P2_B_Defense_Modifier',
  'P2_B_Dizzy_Reset_Timer',
  'P2_B_Dizzy',
  'P2_B_Facing_Right',
  'P2_B_Flight_Flag',
  'P2_B_FlyingScreen',
  'P2_B_FSI_Combo',
  'P2_B_FSI_Points',
  'P2_B_FSI_Projectile',
  'P2_B_GuardBreak_Flag',
  'P2_B_Health_Big',
  'P2_B_Health_Small',
  'P2_B_Hitstop2',
  'P2_B_Hyper_Armor',
  'P2_B_ID_2',
  'P2_B_Idle_Hover',
  'P2_B_Is_Active',
  'P2_B_Is_Point',
  'P2_B_Is_Prox_Block',
  'P2_B_Jumping_Special_Counter',
  'P2_B_Jumps',
  'P2_B_Knockdown_State',
  'P2_B_Landing_Shake',
  'P2_B_Magneto_Throw_Toggle',
  'P2_B_Move_Disable',
  'P2_B_Normal_Held_Direction',
  'P2_B_Normal_Location',
  'P2_B_Normal_Strength',
  'P2_B_Powerup_Modifier',
  'P2_B_Powerup_Timer',
  'P2_B_ProxBlock',
  'P2_B_PunchKick',
  'P2_B_SJ_Counter',
  'P2_B_Snapback_Timer',
  'P2_B_Special_Attack_ID',
  'P2_B_Special_Strength',
  'P2_B_Speedup',
  'P2_B_Stun_Check',
  'P2_B_Super_Armor',
  'P2_B_Throw_Counter_Mash',
  'P2_B_Throw_Immune',
  'P2_B_Throw_Limiter',
  'P2_B_Throw_RNG',
  'P2_B_Trip_Checker',
  'P2_B_Unfly',
  'P2_B_Walking',
  'P2_B_X_Gravity_Max',
  'P2_B_X_Gravity_Min',
  'P2_B_X_Position_Arena_Max',
  'P2_B_X_Position_Arena_Min',
  'P2_B_X_Position_From_Enemy_Max',
  'P2_B_X_Position_From_Enemy_Min',
  'P2_B_X_Position_Screen_Max',
  'P2_B_X_Position_Screen_Min',
  'P2_B_Y_Gravity_Max',
  'P2_B_Y_Gravity_Min',
  'P2_B_Y_Position_Arena_Max',
  'P2_B_Y_Position_Arena_Min',
  'P2_B_Y_Position_From_Enemy_Max',
  'P2_B_Y_Position_From_Enemy_Min',
  'P2_B_Y_Position_Screen_Max',
  'P2_B_Y_Position_Screen_Min',
  'P2_B_X_Velocity_Max',
  'P2_B_X_Velocity_Min',
  'P2_B_Y_Velocity_Max',
  'P2_B_Y_Velocity_Min',
  'P2_B_Bison_214kk_Timer_Max',
  'P2_B_Bison_214kk_Timer_Min',
  'P2_B_Dhalsim_214kk_Timer_Max',
  'P2_B_Dhalsim_214kk_Timer_Min',
  'P2_B_Doom_214kk_Timer_Max',
  'P2_B_Doom_214kk_Timer_Min',
  'P2_B_Iron_Man_214kk_Timer_Max',
  'P2_B_Iron_Man_214kk_Timer_Min',
  'P2_B_Magneto_214kk_Timer_Max',
  'P2_B_Magneto_214kk_Timer_Min',
  'P2_B_Megaman_214kk_Timer_Max',
  'P2_B_Megaman_214kk_Timer_Min',
  'P2_B_Sentinel_214kk_Timer_Max',
  'P2_B_Sentinel_214kk_Timer_Min',
  'P2_B_Storm_214kk_Timer_Max',
  'P2_B_Storm_214kk_Timer_Min',
  'P2_B_War_Machine_214kk_Timer_Max',
  'P2_B_War_Machine_214kk_Timer_Min',
  'P2_B_X_Gravity_0',
  'P2_B_X_Gravity_Min_0',
  'P2_B_X_Gravity_Max_0',
  'P2_B_X_Position_Arena_0',
  'P2_B_X_Position_Arena_Min_0',
  'P2_B_X_Position_Arena_Max_0',
  'P2_B_X_Position_From_Enemy_0',
  'P2_B_X_Position_From_Enemy_Min_0',
  'P2_B_X_Position_From_Enemy_Max_0',
  'P2_B_X_Position_Screen_0',
  'P2_B_X_Position_Screen_Min_0',
  'P2_B_X_Position_Screen_Max_0',
  'P2_B_X_Velocity_0',
  'P2_B_X_Velocity_Min_0',
  'P2_B_X_Velocity_Max_0',
  'P2_B_Y_Gravity_0',
  'P2_B_Y_Gravity_Min_0',
  'P2_B_Y_Gravity_Max_0',
  'P2_B_Y_Position_Arena_0',
  'P2_B_Y_Position_Arena_Min_0',
  'P2_B_Y_Position_Arena_Max_0',
  'P2_B_Y_Position_From_Enemy_0',
  'P2_B_Y_Position_From_Enemy_Min_0',
  'P2_B_Y_Position_From_Enemy_Max_0',
  'P2_B_Y_Position_Screen_0',
  'P2_B_Y_Position_Screen_Min_0',
  'P2_B_Y_Position_Screen_Max_0',
  'P2_B_Y_Velocity_0',
  'P2_B_Y_Velocity_Min_0',
  'P2_B_Y_Velocity_Max_0',
  // * * * P2_C_ * * * //
  'P2_C_Anakaris_SStun_Timer',
  'P2_C_Bison_214kk_Timer',
  'P2_C_Cable_236p_Timer',
  'P2_C_Dhalsim_214kk_Timer',
  'P2_C_Doom_214kk_Timer',
  'P2_C_Iron_Man_214kk_Timer',
  'P2_C_Magneto_214kk_Timer',
  'P2_C_Megaman_214kk_Timer',
  'P2_C_Sentinel_214kk_Timer',
  'P2_C_Storm_214kk_Timer',
  'P2_C_War_Machine_214kk_Timer',
  'P2_C_X_Position_From_Enemy',
  'P2_C_Y_Position_From_Enemy',
  'P2_C_X_Gravity',
  'P2_C_Y_Gravity',
  'P2_C_X_Position_Arena',
  'P2_C_Y_Position_Arena',
  'P2_C_X_Position_Screen',
  'P2_C_Y_Position_Screen',
  'P2_C_X_Velocity',
  'P2_C_Y_Velocity',
  'P2_C_Action_Flags',
  'P2_C_Air_Dash_Count',
  'P2_C_Air_Recovery_Timer',
  'P2_C_Airborne',
  'P2_C_Animation_Lock',
  'P2_C_Animation_Timer_Main',
  'P2_C_Animation_Value',
  'P2_C_Assist_Counter',
  'P2_C_Assist_Onscreen',
  'P2_C_Assist_Value',
  'P2_C_Attack_Immune',
  'P2_C_Attack_Number',
  'P2_C_Block_Meter',
  'P2_C_Block_Stun',
  'P2_C_Color',
  'P2_C_CornerJump',
  'P2_C_Corner_Touch',
  'P2_C_Damage',
  'P2_C_Damage_Modifier',
  'P2_C_Defense_Modifier',
  'P2_C_Dizzy_Reset_Timer',
  'P2_C_Dizzy',
  'P2_C_Facing_Right',
  'P2_C_Flight_Flag',
  'P2_C_FlyingScreen',
  'P2_C_FSI_Combo',
  'P2_C_FSI_Points',
  'P2_C_FSI_Projectile',
  'P2_C_GuardBreak_Flag',
  'P2_C_Health_Big',
  'P2_C_Health_Small',
  'P2_C_Hitstop2',
  'P2_C_Hyper_Armor',
  'P2_C_ID_2',
  'P2_C_Idle_Hover',
  'P2_C_Is_Active',
  'P2_C_Is_Point',
  'P2_C_Is_Prox_Block',
  'P2_C_Jumping_Special_Counter',
  'P2_C_Jumps',
  'P2_C_Knockdown_State',
  'P2_C_Landing_Shake',
  'P2_C_Magneto_Throw_Toggle',
  'P2_C_Move_Disable',
  'P2_C_Normal_Held_Direction',
  'P2_C_Normal_Location',
  'P2_C_Normal_Strength',
  'P2_C_Powerup_Modifier',
  'P2_C_Powerup_Timer',
  'P2_C_ProxBlock',
  'P2_C_PunchKick',
  'P2_C_SJ_Counter',
  'P2_C_Snapback_Timer',
  'P2_C_Special_Attack_ID',
  'P2_C_Special_Strength',
  'P2_C_Speedup',
  'P2_C_Stun_Check',
  'P2_C_Super_Armor',
  'P2_C_Throw_Counter_Mash',
  'P2_C_Throw_Immune',
  'P2_C_Throw_Limiter',
  'P2_C_Throw_RNG',
  'P2_C_Trip_Checker',
  'P2_C_Unfly',
  'P2_C_Walking',
  'P2_C_X_Gravity_Max',
  'P2_C_X_Gravity_Min',
  'P2_C_X_Position_Arena_Max',
  'P2_C_X_Position_Arena_Min',
  'P2_C_X_Position_From_Enemy_Max',
  'P2_C_X_Position_From_Enemy_Min',
  'P2_C_X_Position_Screen_Max',
  'P2_C_X_Position_Screen_Min',
  'P2_C_Y_Gravity_Max',
  'P2_C_Y_Gravity_Min',
  'P2_C_Y_Position_Arena_Max',
  'P2_C_Y_Position_Arena_Min',
  'P2_C_Y_Position_From_Enemy_Max',
  'P2_C_Y_Position_From_Enemy_Min',
  'P2_C_Y_Position_Screen_Max',
  'P2_C_Y_Position_Screen_Min',
  'P2_C_X_Velocity_Max',
  'P2_C_X_Velocity_Min',
  'P2_C_Y_Velocity_Max',
  'P2_C_Y_Velocity_Min',
  'P2_C_Bison_214kk_Timer_Max',
  'P2_C_Bison_214kk_Timer_Min',
  'P2_C_Dhalsim_214kk_Timer_Max',
  'P2_C_Dhalsim_214kk_Timer_Min',
  'P2_C_Doom_214kk_Timer_Max',
  'P2_C_Doom_214kk_Timer_Min',
  'P2_C_Iron_Man_214kk_Timer_Max',
  'P2_C_Iron_Man_214kk_Timer_Min',
  'P2_C_Magneto_214kk_Timer_Max',
  'P2_C_Magneto_214kk_Timer_Min',
  'P2_C_Megaman_214kk_Timer_Max',
  'P2_C_Megaman_214kk_Timer_Min',
  'P2_C_Sentinel_214kk_Timer_Max',
  'P2_C_Sentinel_214kk_Timer_Min',
  'P2_C_Storm_214kk_Timer_Max',
  'P2_C_Storm_214kk_Timer_Min',
  'P2_C_War_Machine_214kk_Timer_Max',
  'P2_C_War_Machine_214kk_Timer_Min',
  'P2_C_X_Gravity_0',
  'P2_C_X_Gravity_Min_0',
  'P2_C_X_Gravity_Max_0',
  'P2_C_X_Position_Arena_0',
  'P2_C_X_Position_Arena_Min_0',
  'P2_C_X_Position_Arena_Max_0',
  'P2_C_X_Position_From_Enemy_0',
  'P2_C_X_Position_From_Enemy_Min_0',
  'P2_C_X_Position_From_Enemy_Max_0',
  'P2_C_X_Position_Screen_0',
  'P2_C_X_Position_Screen_Min_0',
  'P2_C_X_Position_Screen_Max_0',
  'P2_C_X_Velocity_0',
  'P2_C_X_Velocity_Min_0',
  'P2_C_X_Velocity_Max_0',
  'P2_C_Y_Gravity_0',
  'P2_C_Y_Gravity_Min_0',
  'P2_C_Y_Gravity_Max_0',
  'P2_C_Y_Position_Arena_0',
  'P2_C_Y_Position_Arena_Min_0',
  'P2_C_Y_Position_Arena_Max_0',
  'P2_C_Y_Position_From_Enemy_0',
  'P2_C_Y_Position_From_Enemy_Min_0',
  'P2_C_Y_Position_From_Enemy_Max_0',
  'P2_C_Y_Position_Screen_0',
  'P2_C_Y_Position_Screen_Min_0',
  'P2_C_Y_Position_Screen_Max_0',
  'P2_C_Y_Velocity_0',
  'P2_C_Y_Velocity_Min_0',
  'P2_C_Y_Velocity_Max_0',
];
